/* CVS $Id: $ */
 
import org.apache.jena.rdf.model.*;
import org.apache.jena.ontology.*;
 
/**
 * Vocabulary definitions from ontCWAF_0_3.owl 
 * @author Auto-generated by schemagen on 13 juin 2024 15:56 
 */
public class OntCWAF_0_3 {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static final OntModel M_MODEL = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://visualdataweb.org/ontCWAF/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = M_MODEL.createResource( NS );
    
    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "0.3";
    
    public static final ObjectProperty CONTAINS_DIRECTIVE = M_MODEL.createObjectProperty( "http://visualdataweb.org/ontCWAF/containsDirective" );
    
    public static final ObjectProperty CONTAINS_FILE = M_MODEL.createObjectProperty( "http://visualdataweb.org/ontCWAF/containsFile" );
    
    public static final ObjectProperty EMBED_DIRECTIVE = M_MODEL.createObjectProperty( "http://visualdataweb.org/ontCWAF/embedDirective" );
    
    public static final ObjectProperty HAS_LOCATION = M_MODEL.createObjectProperty( "http://visualdataweb.org/ontCWAF/hasLocation" );
    
    public static final ObjectProperty HAS_SCOPE = M_MODEL.createObjectProperty( "http://visualdataweb.org/ontCWAF/hasScope" );
    
    public static final ObjectProperty HAS_SERVER = M_MODEL.createObjectProperty( "http://visualdataweb.org/ontCWAF/hasServer" );
    
    public static final ObjectProperty HAS_VIRTUAL_HOST = M_MODEL.createObjectProperty( "http://visualdataweb.org/ontCWAF/hasVirtualHost" );
    
    public static final ObjectProperty INCLUDE_FILE = M_MODEL.createObjectProperty( "http://visualdataweb.org/ontCWAF/includeFile" );
    
    public static final ObjectProperty USE_MACRO = M_MODEL.createObjectProperty( "http://visualdataweb.org/ontCWAF/useMacro" );
    
    public static final DatatypeProperty ARGUMENTS = M_MODEL.createDatatypeProperty( "http://visualdataweb.org/ontCWAF/arguments" );
    
    public static final DatatypeProperty CONDITION = M_MODEL.createDatatypeProperty( "http://visualdataweb.org/ontCWAF/condition" );
    
    public static final DatatypeProperty CONFIG_NAME = M_MODEL.createDatatypeProperty( "http://visualdataweb.org/ontCWAF/configName" );
    
    public static final DatatypeProperty DIR_LINE_NUM = M_MODEL.createDatatypeProperty( "http://visualdataweb.org/ontCWAF/dirLineNum" );
    
    public static final DatatypeProperty FILE_PATH = M_MODEL.createDatatypeProperty( "http://visualdataweb.org/ontCWAF/filePath" );
    
    public static final DatatypeProperty LOCATION_PATH = M_MODEL.createDatatypeProperty( "http://visualdataweb.org/ontCWAF/locationPath" );
    
    public static final DatatypeProperty MACRO_NAME = M_MODEL.createDatatypeProperty( "http://visualdataweb.org/ontCWAF/macroName" );
    
    public static final DatatypeProperty PHASE = M_MODEL.createDatatypeProperty( "http://visualdataweb.org/ontCWAF/phase" );
    
    public static final DatatypeProperty SERVER_NAME = M_MODEL.createDatatypeProperty( "http://visualdataweb.org/ontCWAF/serverName" );
    
    public static final DatatypeProperty SERVER_PORT = M_MODEL.createDatatypeProperty( "http://visualdataweb.org/ontCWAF/serverPort" );
    
    public static final DatatypeProperty V_HOST_NAME = M_MODEL.createDatatypeProperty( "http://visualdataweb.org/ontCWAF/vHostName" );
    
    public static final OntClass BEACON = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/Beacon" );
    
    public static final OntClass CONFIGURATION = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/Configuration" );
    
    public static final OntClass DIRECTIVE = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/Directive" );
    
    public static final OntClass FILE = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/File" );
    
    public static final OntClass IF = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/If" );
    
    public static final OntClass INCLUDE = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/Include" );
    
    public static final OntClass LOCATION = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/Location" );
    
    public static final OntClass MACRO = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/Macro" );
    
    public static final OntClass MOD_SEC_RULE = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/ModSecRule" );
    
    public static final OntClass RULE = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/Rule" );
    
    public static final OntClass SCOPE = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/Scope" );
    
    public static final OntClass SEC_ACTION = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/SecAction" );
    
    public static final OntClass SEC_RULE = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/SecRule" );
    
    public static final OntClass SERVER = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/Server" );
    
    public static final OntClass USE = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/Use" );
    
    public static final OntClass VIRTUAL_HOST = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/VirtualHost" );
    
}
