/* CVS $Id: $ */
 
import org.apache.jena.rdf.model.*;
import org.apache.jena.ontology.*;
 
/**
 * Vocabulary definitions from ontCWAF_0_2.owl 
 * @author Auto-generated by schemagen on 22 mai 2024 15:26 
 */
public class OntCWAF_0_2 {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static final OntModel M_MODEL = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://visualdataweb.org/ontCWAF/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = M_MODEL.createResource( NS );
    
    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "0.2";
    
    public static final ObjectProperty CONTAINES_DIRECTIVES = M_MODEL.createObjectProperty( "http://visualdataweb.org/ontCWAF/containesDirectives" );
    
    public static final ObjectProperty CONTAINS_DIRECTIVE = M_MODEL.createObjectProperty( "http://visualdataweb.org/ontCWAF/containsDirective" );
    
    public static final ObjectProperty CONTAINS_FILES = M_MODEL.createObjectProperty( "http://visualdataweb.org/ontCWAF/containsFiles" );
    
    public static final ObjectProperty FIRST = M_MODEL.createObjectProperty( "http://visualdataweb.org/ontCWAF/first" );
    
    public static final ObjectProperty HAS_CONDITION = M_MODEL.createObjectProperty( "http://visualdataweb.org/ontCWAF/hasCondition" );
    
    public static final ObjectProperty HAS_LOCATION = M_MODEL.createObjectProperty( "http://visualdataweb.org/ontCWAF/hasLocation" );
    
    public static final ObjectProperty HAS_METADATA = M_MODEL.createObjectProperty( "http://visualdataweb.org/ontCWAF/hasMetadata" );
    
    public static final ObjectProperty HAS_SCOPE = M_MODEL.createObjectProperty( "http://visualdataweb.org/ontCWAF/hasScope" );
    
    public static final ObjectProperty HAS_SERVER = M_MODEL.createObjectProperty( "http://visualdataweb.org/ontCWAF/hasServer" );
    
    public static final ObjectProperty HAS_VIRTUAL_HOST = M_MODEL.createObjectProperty( "http://visualdataweb.org/ontCWAF/hasVirtualHost" );
    
    public static final ObjectProperty HAS_GLOBALS = M_MODEL.createObjectProperty( "http://visualdataweb.org/ontCWAF/has_globals" );
    
    public static final ObjectProperty OPERATOR = M_MODEL.createObjectProperty( "http://visualdataweb.org/ontCWAF/operator" );
    
    public static final ObjectProperty SECOND = M_MODEL.createObjectProperty( "http://visualdataweb.org/ontCWAF/second" );
    
    public static final ObjectProperty TBD = M_MODEL.createObjectProperty( "http://visualdataweb.org/ontCWAF/tbd" );
    
    public static final DatatypeProperty CONFIG_NAME = M_MODEL.createDatatypeProperty( "http://visualdataweb.org/ontCWAF/configName" );
    
    public static final DatatypeProperty DEF_LINE_NUM = M_MODEL.createDatatypeProperty( "http://visualdataweb.org/ontCWAF/defLineNUm" );
    
    public static final DatatypeProperty DEFINE_STR_VALUE = M_MODEL.createDatatypeProperty( "http://visualdataweb.org/ontCWAF/defineStrValue" );
    
    public static final DatatypeProperty FILEPATH = M_MODEL.createDatatypeProperty( "http://visualdataweb.org/ontCWAF/filepath" );
    
    public static final DatatypeProperty LINE_NUM = M_MODEL.createDatatypeProperty( "http://visualdataweb.org/ontCWAF/lineNum" );
    
    public static final DatatypeProperty LISTEN = M_MODEL.createDatatypeProperty( "http://visualdataweb.org/ontCWAF/listen" );
    
    public static final DatatypeProperty LOCATION_PATH = M_MODEL.createDatatypeProperty( "http://visualdataweb.org/ontCWAF/locationPath" );
    
    public static final DatatypeProperty MACRO_NAME = M_MODEL.createDatatypeProperty( "http://visualdataweb.org/ontCWAF/macroName" );
    
    public static final DatatypeProperty MESSAGE = M_MODEL.createDatatypeProperty( "http://visualdataweb.org/ontCWAF/message" );
    
    public static final DatatypeProperty META_DATA_ID = M_MODEL.createDatatypeProperty( "http://visualdataweb.org/ontCWAF/metaDataId" );
    
    public static final DatatypeProperty PHSE = M_MODEL.createDatatypeProperty( "http://visualdataweb.org/ontCWAF/phse" );
    
    public static final DatatypeProperty REVISION_NUMBER = M_MODEL.createDatatypeProperty( "http://visualdataweb.org/ontCWAF/revisionNumber" );
    
    public static final DatatypeProperty RULE_ID = M_MODEL.createDatatypeProperty( "http://visualdataweb.org/ontCWAF/ruleId" );
    
    public static final DatatypeProperty SERVER_NAME = M_MODEL.createDatatypeProperty( "http://visualdataweb.org/ontCWAF/serverName" );
    
    public static final DatatypeProperty TAG = M_MODEL.createDatatypeProperty( "http://visualdataweb.org/ontCWAF/tag" );
    
    public static final DatatypeProperty VIRTUAL_HOST_NAME = M_MODEL.createDatatypeProperty( "http://visualdataweb.org/ontCWAF/virtualHostName" );
    
    public static final DatatypeProperty VIRTUAL_HOST_PORT = M_MODEL.createDatatypeProperty( "http://visualdataweb.org/ontCWAF/virtualHostPort" );
    
    public static final OntClass CLASS44 = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/Class44" );
    
    public static final OntClass CONDITION = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/Condition" );
    
    public static final OntClass CONFIGURATION = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/Configuration" );
    
    public static final OntClass DEFINE = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/Define" );
    
    public static final OntClass DEFINE_STR = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/DefineStr" );
    
    public static final OntClass DIRECTIVE = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/Directive" );
    
    public static final OntClass FILE = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/File" );
    
    public static final OntClass IF_DEFINED = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/IfDefined" );
    
    public static final OntClass LOCATION = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/Location" );
    
    public static final OntClass MACRO = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/Macro" );
    
    public static final OntClass META_DATA = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/MetaData" );
    
    public static final OntClass OPERATOR_CLASS = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/Operator" );
    
    public static final OntClass RULE = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/Rule" );
    
    public static final OntClass SCOPE = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/Scope" );
    
    public static final OntClass SERVER = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/Server" );
    
    public static final OntClass VIRTUAL_HOST = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/VirtualHost" );
    
    public static final OntClass EQUALS = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/equals" );
    
    public static final OntClass FIRST_OPERAND = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/firstOperand" );
    
    public static final OntClass GREATHER_OPERATOR = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/greatherOperator" );
    
    public static final OntClass LESS_THAN_OPERATOR = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/lessThanOperator" );
    
    public static final OntClass SECOND_OPERAND = M_MODEL.createClass( "http://visualdataweb.org/ontCWAF/secondOperand" );
    
}
